[package]
name = "foks-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "foks-agent"
path = "src/main.rs"

[dependencies]
foks-oidc = { workspace = true }
clap = { workspace = true }
foks-agent-proto = { workspace = true }
foks-client = { workspace = true }
foks-crypto = { workspace = true }
foks-client-app = { workspace = true }
foks-client-db = { workspace = true }
foks-compat-artifact = { workspace = true }
foks-go-interop = { workspace = true }
foks-keystore = { workspace = true }
foks-proto = { workspace = true }
foks-rpc = { workspace = true }
foks-verify = { workspace = true }
foks-yubi = { workspace = true, features = ["hardware"] }
fs2 = { workspace = true }
getrandom = { workspace = true }
libc = { workspace = true }
reqwest = { workspace = true }
rustix = { workspace = true, features = ["net"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
foks-server-db = { workspace = true }
foks-server-testkit = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
