use foks_rpc::{
    KV_CACHE_CHECK_METHOD_POSITION, KV_FILE_UPLOAD_CHUNK_METHOD_POSITION,
    KV_FILE_UPLOAD_INIT_METHOD_POSITION, KV_GET_DIR_METHOD_POSITION,
    KV_GET_ENCRYPTED_CHUNK_METHOD_POSITION, KV_GET_NODE_METHOD_POSITION,
    KV_GET_ROOT_METHOD_POSITION, KV_LIST_METHOD_POSITION, KV_LOCK_ACQUIRE_METHOD_POSITION,
    KV_LOCK_RELEASE_METHOD_POSITION, KV_MKDIR_METHOD_POSITION, KV_PUT_METHOD_POSITION,
    KV_PUT_ROOT_METHOD_POSITION, KV_PUT_SMALL_FILE_OR_SYMLINK_METHOD_POSITION,
    KV_SELECT_VHOST_METHOD_POSITION, KV_STORE_PROTOCOL_ID, MERKLE_GET_CURRENT_ROOT_METHOD_POSITION,
    MERKLE_GET_HISTORICAL_ROOTS_METHOD_POSITION, MERKLE_QUERY_PROTOCOL_ID,
    MERKLE_SELECT_VHOST_METHOD_POSITION, PROBE_METHOD_POSITION, PROBE_PROTOCOL_ID,
    REG_GET_CLIENT_CERT_CHAIN_METHOD_POSITION, REG_PROTOCOL_ID,
    REG_RESERVE_USERNAME_METHOD_POSITION, REG_SELECT_VHOST_METHOD_POSITION,
    REG_SIGNUP_METHOD_POSITION, USER_GET_HOST_CONFIG_METHOD_POSITION,
    USER_GET_PUK_FOR_ROLE_METHOD_POSITION, USER_LOAD_USER_CHAIN_METHOD_POSITION, USER_PROTOCOL_ID,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ServiceSpec {
    pub name: &'static str,
    pub service_type: u64,
    pub listener: &'static str,
    pub supported: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RouteSpec {
    pub protocol: &'static str,
    pub protocol_id: u64,
    pub method: &'static str,
    pub position: u64,
    pub listener: &'static str,
    pub authentication: &'static str,
    pub request: &'static str,
    pub result: &'static str,
    pub statuses: &'static [&'static str],
    pub max_request_bytes: usize,
    pub supported: bool,
}

pub const SERVICES: &[ServiceSpec] = &[
    ServiceSpec {
        name: "registration",
        service_type: 1,
        listener: "public_services",
        supported: true,
    },
    ServiceSpec {
        name: "user",
        service_type: 2,
        listener: "authenticated",
        supported: true,
    },
    ServiceSpec {
        name: "merkle_query",
        service_type: 5,
        listener: "public_services",
        supported: true,
    },
    ServiceSpec {
        name: "probe",
        service_type: 10,
        listener: "probe",
        supported: true,
    },
    ServiceSpec {
        name: "kv_store",
        service_type: 12,
        listener: "authenticated",
        supported: true,
    },
    ServiceSpec {
        name: "realtime",
        service_type: 16,
        listener: "authenticated",
        supported: false,
    },
];

const BASIC: &[&str] = &["ok", "bad_args", "not_found"];
const KV_WRITE: &[&str] = &["ok", "bad_args", "stale_cache", "quota_exceeded"];
const KV_READ: &[&str] = &["ok", "bad_args", "kv_noent"];

pub const ROUTES: &[RouteSpec] = &[
    RouteSpec {
        protocol: "Probe",
        protocol_id: PROBE_PROTOCOL_ID,
        method: "probe",
        position: PROBE_METHOD_POSITION,
        listener: "probe",
        authentication: "public",
        request: "ProbeArgument",
        result: "ProbeResponse",
        statuses: &["ok", "bad_args", "unsupported"],
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "reserveUsername",
        position: REG_RESERVE_USERNAME_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "ReserveUsernameArgument",
        result: "UsernameReservation",
        statuses: &["ok", "bad_args", "name_in_use", "rate_limited"],
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "getClientCertChain",
        position: REG_GET_CLIENT_CERT_CHAIN_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "ClientCertChainArgument",
        result: "CertificateChain",
        statuses: &["ok", "bad_args", "not_found", "rate_limited"],
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "signup",
        position: REG_SIGNUP_METHOD_POSITION,
        listener: "public_services",
        authentication: "signed_signup",
        request: "SoftwareSignupArgument",
        result: "Void",
        statuses: &["ok", "bad_args", "name_in_use", "stale_root", "tx_retry"],
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "selectVHost",
        position: REG_SELECT_VHOST_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "SelectVHostArgument",
        result: "Void",
        statuses: BASIC,
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "User",
        protocol_id: USER_PROTOCOL_ID,
        method: "loadUserChain",
        position: USER_LOAD_USER_CHAIN_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "LoadUserChainArgument",
        result: "UserChain",
        statuses: &["ok", "bad_args", "not_found", "permission_denied"],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "User",
        protocol_id: USER_PROTOCOL_ID,
        method: "getPukForRole",
        position: USER_GET_PUK_FOR_ROLE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "GetPukForRoleArgument",
        result: "SharedKeyParcel",
        statuses: &["ok", "bad_args", "not_found", "permission_denied"],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "User",
        protocol_id: USER_PROTOCOL_ID,
        method: "getHostConfig",
        position: USER_GET_HOST_CONFIG_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "Void",
        result: "Unsupported",
        statuses: &["unsupported"],
        max_request_bytes: 1024,
        supported: false,
    },
    RouteSpec {
        protocol: "MerkleQuery",
        protocol_id: MERKLE_QUERY_PROTOCOL_ID,
        method: "getHistoricalRoots",
        position: MERKLE_GET_HISTORICAL_ROOTS_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "HistoricalMerkleRootsArgument",
        result: "HistoricalMerkleRoots",
        statuses: BASIC,
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "MerkleQuery",
        protocol_id: MERKLE_QUERY_PROTOCOL_ID,
        method: "getCurrentRoot",
        position: MERKLE_GET_CURRENT_ROOT_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "CurrentMerkleRootArgument",
        result: "MerkleRoot",
        statuses: BASIC,
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "MerkleQuery",
        protocol_id: MERKLE_QUERY_PROTOCOL_ID,
        method: "selectVHost",
        position: MERKLE_SELECT_VHOST_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "SelectVHostArgument",
        result: "Void",
        statuses: BASIC,
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "mkdir",
        position: KV_MKDIR_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvMkdirArgument",
        result: "KvDirectory",
        statuses: KV_WRITE,
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "put",
        position: KV_PUT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvPutArgument",
        result: "KvDirectory",
        statuses: KV_WRITE,
        max_request_bytes: 4_194_304,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "putRoot",
        position: KV_PUT_ROOT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvPutRootArgument",
        result: "Void",
        statuses: KV_WRITE,
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "fileUploadInit",
        position: KV_FILE_UPLOAD_INIT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvUploadInitArgument",
        result: "Void",
        statuses: KV_WRITE,
        max_request_bytes: 16_777_216,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "fileUploadChunk",
        position: KV_FILE_UPLOAD_CHUNK_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvUploadChunkArgument",
        result: "Void",
        statuses: &["ok", "bad_args", "not_found", "quota_exceeded"],
        max_request_bytes: 16_777_216,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "putSmallFileOrSymlink",
        position: KV_PUT_SMALL_FILE_OR_SYMLINK_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvPutSmallArgument",
        result: "Void",
        statuses: KV_WRITE,
        max_request_bytes: 4_194_304,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "getRoot",
        position: KV_GET_ROOT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvGetRootArgument",
        result: "KvRoot",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "getNode",
        position: KV_GET_NODE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvGetNodeArgument",
        result: "KvNode",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "getEncryptedChunk",
        position: KV_GET_ENCRYPTED_CHUNK_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvGetChunkArgument",
        result: "KvEncryptedChunk",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "getDir",
        position: KV_GET_DIR_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvGetDirArgument",
        result: "KvDirectory",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "cacheCheck",
        position: KV_CACHE_CHECK_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvCacheCheckArgument",
        result: "KvPathVersionVector",
        statuses: &["ok", "bad_args", "stale_cache"],
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "list",
        position: KV_LIST_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvListArgument",
        result: "KvList",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "lockAcquire",
        position: KV_LOCK_ACQUIRE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvLockAcquireArgument",
        result: "KvLock",
        statuses: &["ok", "bad_args", "locked"],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "lockRelease",
        position: KV_LOCK_RELEASE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvLockReleaseArgument",
        result: "Void",
        statuses: BASIC,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "selectVHost",
        position: KV_SELECT_VHOST_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "SelectVHostArgument",
        result: "Void",
        statuses: BASIC,
        max_request_bytes: 4096,
        supported: true,
    },
];

/// Resolves a wire dispatch key without allocating or accepting an unknown method.
pub fn route(protocol_id: u64, position: u64) -> Option<&'static RouteSpec> {
    ROUTES
        .iter()
        .find(|route| route.protocol_id == protocol_id && route.position == position)
}
