use foks_rpc::{
    KV_CACHE_CHECK_METHOD_POSITION, KV_FILE_UPLOAD_CHUNK_METHOD_POSITION,
    KV_FILE_UPLOAD_INIT_METHOD_POSITION, KV_GET_DIR_METHOD_POSITION,
    KV_GET_ENCRYPTED_CHUNK_METHOD_POSITION, KV_GET_NODE_METHOD_POSITION,
    KV_GET_ROOT_METHOD_POSITION, KV_LIST_METHOD_POSITION, KV_LOCK_ACQUIRE_METHOD_POSITION,
    KV_LOCK_RELEASE_METHOD_POSITION, KV_MKDIR_METHOD_POSITION, KV_PUT_METHOD_POSITION,
    KV_PUT_ROOT_METHOD_POSITION, KV_PUT_SMALL_FILE_OR_SYMLINK_METHOD_POSITION,
    KV_SELECT_VHOST_METHOD_POSITION, KV_STORE_PROTOCOL_ID, MERKLE_GET_CURRENT_ROOT_METHOD_POSITION,
    MERKLE_GET_HISTORICAL_ROOTS_METHOD_POSITION, MERKLE_QUERY_PROTOCOL_ID,
    MERKLE_SELECT_VHOST_METHOD_POSITION, PROBE_METHOD_POSITION, PROBE_PROTOCOL_ID,
    REG_GET_CLIENT_CERT_CHAIN_METHOD_POSITION, REG_GET_UID_LOOKUP_CHALLENGE_METHOD_POSITION,
    REG_LOOKUP_UID_BY_DEVICE_METHOD_POSITION, REG_PROTOCOL_ID,
    REG_RESERVE_USERNAME_METHOD_POSITION, REG_SELECT_VHOST_METHOD_POSITION,
    REG_SIGNUP_METHOD_POSITION, TEAM_ACTIVATE_BEARER_TOKEN_METHOD_POSITION,
    TEAM_ACTIVATE_VIEW_METHOD_POSITION, TEAM_ADMIN_PROTOCOL_ID, TEAM_CREATE_NAMED_METHOD_POSITION,
    TEAM_EDIT_METHOD_POSITION, TEAM_GET_VIEW_CHALLENGE_METHOD_POSITION, TEAM_LOADER_PROTOCOL_ID,
    TEAM_LOAD_CHAIN_METHOD_POSITION, TEAM_LOAD_REMOVAL_KEY_BOX_METHOD_POSITION,
    TEAM_MAKE_INERT_BEARER_TOKEN_METHOD_POSITION, TEAM_RESERVE_NAME_METHOD_POSITION,
    USER_GET_HOST_CONFIG_METHOD_POSITION, USER_GET_PUK_FOR_ROLE_METHOD_POSITION,
    USER_LOAD_USER_CHAIN_METHOD_POSITION, USER_PROTOCOL_ID, USER_PROVISION_DEVICE_METHOD_POSITION,
    USER_REVOKE_DEVICE_METHOD_POSITION,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ServiceSpec {
    pub name: &'static str,
    pub service_type: u64,
    pub listener: &'static str,
    pub supported: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RouteSpec {
    pub protocol: &'static str,
    pub protocol_id: u64,
    pub method: &'static str,
    pub position: u64,
    pub listener: &'static str,
    pub authentication: &'static str,
    pub request: &'static str,
    pub result: &'static str,
    pub statuses: &'static [&'static str],
    pub max_request_bytes: usize,
    pub supported: bool,
}

pub const SERVICES: &[ServiceSpec] = &[
    ServiceSpec {
        name: "registration",
        service_type: 1,
        listener: "public_services",
        supported: true,
    },
    ServiceSpec {
        name: "user",
        service_type: 2,
        listener: "authenticated",
        supported: true,
    },
    ServiceSpec {
        name: "merkle_query",
        service_type: 5,
        listener: "public_services",
        supported: true,
    },
    ServiceSpec {
        name: "probe",
        service_type: 10,
        listener: "probe",
        supported: true,
    },
    ServiceSpec {
        name: "kv_store",
        service_type: 12,
        listener: "authenticated",
        supported: true,
    },
    ServiceSpec {
        name: "realtime",
        service_type: 16,
        listener: "authenticated",
        supported: false,
    },
];

const BASIC: &[&str] = &["ok", "bad_args", "not_found"];
const KV_WRITE: &[&str] = &["ok", "bad_args", "stale_cache", "quota_exceeded"];
const KV_READ: &[&str] = &["ok", "bad_args", "kv_noent"];

macro_rules! unsupported_team_admin {
    ($method:literal, $position:literal, $authentication:literal, $maximum:literal) => {
        RouteSpec {
            protocol: "TeamAdmin",
            protocol_id: TEAM_ADMIN_PROTOCOL_ID,
            method: $method,
            position: $position,
            listener: "authenticated",
            authentication: $authentication,
            request: "Unsupported",
            result: "Unsupported",
            statuses: &["unsupported"],
            max_request_bytes: $maximum,
            supported: false,
        }
    };
}

pub const ROUTES: &[RouteSpec] = &[
    RouteSpec {
        protocol: "Probe",
        protocol_id: PROBE_PROTOCOL_ID,
        method: "probe",
        position: PROBE_METHOD_POSITION,
        listener: "probe",
        authentication: "public",
        request: "ProbeArgument",
        result: "ProbeResponse",
        statuses: &["ok", "bad_args", "unsupported"],
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "reserveUsername",
        position: REG_RESERVE_USERNAME_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "ReserveUsernameArgument",
        result: "UsernameReservation",
        statuses: &["ok", "bad_args", "name_in_use", "rate_limited"],
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "getClientCertChain",
        position: REG_GET_CLIENT_CERT_CHAIN_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "ClientCertChainArgument",
        result: "CertificateChain",
        statuses: &["ok", "bad_args", "not_found", "rate_limited"],
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "signup",
        position: REG_SIGNUP_METHOD_POSITION,
        listener: "public_services",
        authentication: "signed_signup",
        request: "SoftwareSignupArgument",
        result: "Void",
        statuses: &["ok", "bad_args", "name_in_use", "stale_root", "tx_retry"],
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "getUIDLookupChallege",
        position: REG_GET_UID_LOOKUP_CHALLENGE_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "EntityId",
        result: "RegistrationChallenge",
        statuses: &["ok", "bad_args", "rate_limited"],
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "lookupUIDByDevice",
        position: REG_LOOKUP_UID_BY_DEVICE_METHOD_POSITION,
        listener: "public_services",
        authentication: "signed_lookup_challenge",
        request: "LookupUIDByDeviceArgument",
        result: "LookupUserResult",
        statuses: &[
            "ok",
            "bad_args",
            "expired",
            "not_found",
            "permission_denied",
        ],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "Reg",
        protocol_id: REG_PROTOCOL_ID,
        method: "selectVHost",
        position: REG_SELECT_VHOST_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "SelectVHostArgument",
        result: "Void",
        statuses: BASIC,
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "User",
        protocol_id: USER_PROTOCOL_ID,
        method: "provisionDevice",
        position: USER_PROVISION_DEVICE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_credential_mtls",
        request: "ProvisionDeviceArgument",
        result: "Void",
        statuses: &[
            "ok",
            "bad_args",
            "device_already_provisioned",
            "permission_denied",
            "stale_root",
            "tx_retry",
        ],
        max_request_bytes: 4_194_304,
        supported: true,
    },
    RouteSpec {
        protocol: "User",
        protocol_id: USER_PROTOCOL_ID,
        method: "revokeDevice",
        position: USER_REVOKE_DEVICE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "RevokeDeviceArgument",
        result: "Void",
        statuses: &[
            "ok",
            "bad_args",
            "permission_denied",
            "stale_root",
            "tx_retry",
        ],
        max_request_bytes: 4_194_304,
        supported: true,
    },
    RouteSpec {
        protocol: "User",
        protocol_id: USER_PROTOCOL_ID,
        method: "loadUserChain",
        position: USER_LOAD_USER_CHAIN_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "LoadUserChainArgument",
        result: "UserChain",
        statuses: &["ok", "bad_args", "not_found", "permission_denied"],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "User",
        protocol_id: USER_PROTOCOL_ID,
        method: "getPukForRole",
        position: USER_GET_PUK_FOR_ROLE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "GetPukForRoleArgument",
        result: "SharedKeyParcel",
        statuses: &["ok", "bad_args", "not_found", "permission_denied"],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "User",
        protocol_id: USER_PROTOCOL_ID,
        method: "getHostConfig",
        position: USER_GET_HOST_CONFIG_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "Void",
        result: "HostConfig",
        statuses: &["ok", "permission_denied"],
        max_request_bytes: 1024,
        supported: true,
    },
    RouteSpec {
        protocol: "TeamLoader",
        protocol_id: TEAM_LOADER_PROTOCOL_ID,
        method: "getTeamVOBearerTokenChallenge",
        position: TEAM_GET_VIEW_CHALLENGE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "TeamViewRequest",
        result: "TeamViewChallenge",
        statuses: &[
            "ok",
            "bad_args",
            "team_not_found",
            "team_roster",
            "permission_denied",
        ],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "TeamLoader",
        protocol_id: TEAM_LOADER_PROTOCOL_ID,
        method: "activateTeamVOBearerToken",
        position: TEAM_ACTIVATE_VIEW_METHOD_POSITION,
        listener: "authenticated",
        authentication: "current_puk_signature",
        request: "ActivateTeamViewArgument",
        result: "ActivatedTeamView",
        statuses: &[
            "ok",
            "bad_args",
            "expired",
            "team_bearer_token_stale",
            "team_not_found",
            "team_roster",
            "permission_denied",
        ],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "TeamLoader",
        protocol_id: TEAM_LOADER_PROTOCOL_ID,
        method: "checkTeamVOBearerToken",
        position: 2,
        listener: "authenticated",
        authentication: "active_team_view_token",
        request: "TeamViewToken",
        result: "Unsupported",
        statuses: &["unsupported"],
        max_request_bytes: 4096,
        supported: false,
    },
    RouteSpec {
        protocol: "TeamLoader",
        protocol_id: TEAM_LOADER_PROTOCOL_ID,
        method: "loadTeamChain",
        position: TEAM_LOAD_CHAIN_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_team_view_token",
        request: "LoadTeamChainArgument",
        result: "TeamChain",
        statuses: &[
            "ok",
            "bad_args",
            "expired",
            "team_bearer_token_stale",
            "team_not_found",
            "permission_denied",
        ],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "TeamLoader",
        protocol_id: TEAM_LOADER_PROTOCOL_ID,
        method: "loadTeamMembershipChain",
        position: 4,
        listener: "authenticated",
        authentication: "active_team_view_token",
        request: "Unsupported",
        result: "Unsupported",
        statuses: &["unsupported"],
        max_request_bytes: 4096,
        supported: false,
    },
    RouteSpec {
        protocol: "TeamLoader",
        protocol_id: TEAM_LOADER_PROTOCOL_ID,
        method: "loadRemovalForMember",
        position: 5,
        listener: "authenticated",
        authentication: "active_team_view_token",
        request: "Unsupported",
        result: "Unsupported",
        statuses: &["unsupported"],
        max_request_bytes: 4096,
        supported: false,
    },
    RouteSpec {
        protocol: "TeamLoader",
        protocol_id: TEAM_LOADER_PROTOCOL_ID,
        method: "loadTeamRemoteViewTokens",
        position: 6,
        listener: "authenticated",
        authentication: "active_team_view_token",
        request: "Unsupported",
        result: "Unsupported",
        statuses: &["unsupported"],
        max_request_bytes: 4096,
        supported: false,
    },
    RouteSpec {
        protocol: "TeamLoader",
        protocol_id: TEAM_LOADER_PROTOCOL_ID,
        method: "getServerConfig",
        position: 7,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "Unsupported",
        result: "Unsupported",
        statuses: &["unsupported"],
        max_request_bytes: 1024,
        supported: false,
    },
    RouteSpec {
        protocol: "TeamAdmin",
        protocol_id: TEAM_ADMIN_PROTOCOL_ID,
        method: "reserveTeamname",
        position: TEAM_RESERVE_NAME_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_owner_device_mtls",
        request: "TeamName",
        result: "TeamNameReservation",
        statuses: &["ok", "bad_args", "name_in_use", "rate_limited"],
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "TeamAdmin",
        protocol_id: TEAM_ADMIN_PROTOCOL_ID,
        method: "createTeam",
        position: TEAM_CREATE_NAMED_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_owner_device_mtls",
        request: "NamedTeamCreateArgument",
        result: "Void",
        statuses: &[
            "ok",
            "bad_args",
            "name_in_use",
            "team_error",
            "team_race",
            "team_roster",
            "team_key",
            "stale_root",
            "tx_retry",
        ],
        max_request_bytes: 8_388_608,
        supported: true,
    },
    RouteSpec {
        protocol: "TeamAdmin",
        protocol_id: TEAM_ADMIN_PROTOCOL_ID,
        method: "editTeam",
        position: TEAM_EDIT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "current_team_admin",
        request: "TeamEditArgument",
        result: "TeamEditResult",
        statuses: &[
            "ok",
            "bad_args",
            "team_error",
            "team_race",
            "team_roster",
            "team_key",
            "team_no_source_role",
            "team_removal_key",
            "team_adhoc_invalid_change",
            "stale_root",
            "tx_retry",
        ],
        max_request_bytes: 8_388_608,
        supported: true,
    },
    RouteSpec {
        protocol: "TeamAdmin",
        protocol_id: TEAM_ADMIN_PROTOCOL_ID,
        method: "makeInertTeamBearerToken",
        position: TEAM_MAKE_INERT_BEARER_TOKEN_METHOD_POSITION,
        listener: "authenticated",
        authentication: "current_team_admin",
        request: "MakeInertTeamBearerTokenArgument",
        result: "TeamBearerToken",
        statuses: &[
            "ok",
            "bad_args",
            "team_not_found",
            "team_no_source_role",
            "permission_denied",
        ],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "TeamAdmin",
        protocol_id: TEAM_ADMIN_PROTOCOL_ID,
        method: "activateTeamBearerToken",
        position: TEAM_ACTIVATE_BEARER_TOKEN_METHOD_POSITION,
        listener: "authenticated",
        authentication: "current_ptk_signature",
        request: "ActivateTeamBearerTokenArgument",
        result: "Void",
        statuses: &[
            "ok",
            "bad_args",
            "expired",
            "team_bearer_token_stale",
            "permission_denied",
        ],
        max_request_bytes: 16_384,
        supported: true,
    },
    unsupported_team_admin!("checkTeamBearerToken", 5, "active_team_admin_token", 4096),
    unsupported_team_admin!("putTeamCert", 6, "active_team_admin_token", 4096),
    unsupported_team_admin!("getCurrentTeamCerts", 7, "active_team_admin_token", 4096),
    unsupported_team_admin!("loadTeamRemoteJoinReq", 8, "active_team_admin_token", 4096),
    unsupported_team_admin!("postTeamMembershipLink", 9, "active_team_admin_token", 4096),
    RouteSpec {
        protocol: "TeamAdmin",
        protocol_id: TEAM_ADMIN_PROTOCOL_ID,
        method: "loadRemovalKeyBoxForTeamAdmin",
        position: TEAM_LOAD_REMOVAL_KEY_BOX_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_team_admin_token",
        request: "LoadRemovalKeyBoxArgument",
        result: "TeamRemovalKeyBox",
        statuses: &[
            "ok",
            "bad_args",
            "expired",
            "team_bearer_token_stale",
            "team_removal_key",
            "permission_denied",
        ],
        max_request_bytes: 16_384,
        supported: true,
    },
    unsupported_team_admin!("postTeamRemoval", 11, "active_team_admin_token", 4096),
    unsupported_team_admin!("loadTeamRawInbox", 12, "active_team_admin_token", 4096),
    unsupported_team_admin!("rejectJoinReq", 13, "active_team_admin_token", 4096),
    unsupported_team_admin!("getTeamConfig", 14, "active_device_mtls", 1024),
    RouteSpec {
        protocol: "TeamAdmin",
        protocol_id: TEAM_ADMIN_PROTOCOL_ID,
        method: "createTeamAdHoc",
        position: 15,
        listener: "authenticated",
        authentication: "active_owner_device_mtls",
        request: "AdHocTeamCreateArgument",
        result: "Void",
        statuses: &[
            "ok",
            "bad_args",
            "team_error",
            "team_roster",
            "team_key",
            "team_adhoc_creator_included",
            "team_adhoc_open_viewership",
            "team_adhoc_duplicate",
            "stale_root",
            "tx_retry",
        ],
        max_request_bytes: 8_388_608,
        supported: true,
    },
    RouteSpec {
        protocol: "MerkleQuery",
        protocol_id: MERKLE_QUERY_PROTOCOL_ID,
        method: "getHistoricalRoots",
        position: MERKLE_GET_HISTORICAL_ROOTS_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "HistoricalMerkleRootsArgument",
        result: "HistoricalMerkleRoots",
        statuses: BASIC,
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "MerkleQuery",
        protocol_id: MERKLE_QUERY_PROTOCOL_ID,
        method: "getCurrentRoot",
        position: MERKLE_GET_CURRENT_ROOT_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "CurrentMerkleRootArgument",
        result: "MerkleRoot",
        statuses: BASIC,
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "MerkleQuery",
        protocol_id: MERKLE_QUERY_PROTOCOL_ID,
        method: "selectVHost",
        position: MERKLE_SELECT_VHOST_METHOD_POSITION,
        listener: "public_services",
        authentication: "delegated_tls",
        request: "SelectVHostArgument",
        result: "Void",
        statuses: BASIC,
        max_request_bytes: 4096,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "mkdir",
        position: KV_MKDIR_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvMkdirArgument",
        result: "KvDirectory",
        statuses: KV_WRITE,
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "put",
        position: KV_PUT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvPutArgument",
        result: "KvDirectory",
        statuses: KV_WRITE,
        max_request_bytes: 4_194_304,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "putRoot",
        position: KV_PUT_ROOT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvPutRootArgument",
        result: "Void",
        statuses: KV_WRITE,
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "fileUploadInit",
        position: KV_FILE_UPLOAD_INIT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvUploadInitArgument",
        result: "Void",
        statuses: KV_WRITE,
        max_request_bytes: 16_777_216,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "fileUploadChunk",
        position: KV_FILE_UPLOAD_CHUNK_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvUploadChunkArgument",
        result: "Void",
        statuses: &["ok", "bad_args", "not_found", "quota_exceeded"],
        max_request_bytes: 16_777_216,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "putSmallFileOrSymlink",
        position: KV_PUT_SMALL_FILE_OR_SYMLINK_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvPutSmallArgument",
        result: "Void",
        statuses: KV_WRITE,
        max_request_bytes: 4_194_304,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "getRoot",
        position: KV_GET_ROOT_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvGetRootArgument",
        result: "KvRoot",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "getNode",
        position: KV_GET_NODE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvGetNodeArgument",
        result: "KvNode",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "getEncryptedChunk",
        position: KV_GET_ENCRYPTED_CHUNK_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvGetChunkArgument",
        result: "KvEncryptedChunk",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "getDir",
        position: KV_GET_DIR_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvGetDirArgument",
        result: "KvDirectory",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "cacheCheck",
        position: KV_CACHE_CHECK_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvCacheCheckArgument",
        result: "KvPathVersionVector",
        statuses: &["ok", "bad_args", "stale_cache"],
        max_request_bytes: 1_048_576,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "list",
        position: KV_LIST_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvListArgument",
        result: "KvList",
        statuses: KV_READ,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "lockAcquire",
        position: KV_LOCK_ACQUIRE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvLockAcquireArgument",
        result: "KvLock",
        statuses: &["ok", "bad_args", "locked"],
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "lockRelease",
        position: KV_LOCK_RELEASE_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "KvLockReleaseArgument",
        result: "Void",
        statuses: BASIC,
        max_request_bytes: 16_384,
        supported: true,
    },
    RouteSpec {
        protocol: "KvStore",
        protocol_id: KV_STORE_PROTOCOL_ID,
        method: "selectVHost",
        position: KV_SELECT_VHOST_METHOD_POSITION,
        listener: "authenticated",
        authentication: "active_device_mtls",
        request: "SelectVHostArgument",
        result: "Void",
        statuses: BASIC,
        max_request_bytes: 4096,
        supported: true,
    },
];

/// Resolves a wire dispatch key without allocating or accepting an unknown method.
pub fn route(protocol_id: u64, position: u64) -> Option<&'static RouteSpec> {
    ROUTES
        .iter()
        .find(|route| route.protocol_id == protocol_id && route.position == position)
}
