[package]
name = "foks-client-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = { workspace = true }
rustix = { version = "1.1", features = ["fs", "process"] }
foks-agent-proto = { workspace = true }
foks-oidc = { workspace = true }
foks-client = { workspace = true }
foks-client-db = { workspace = true }
foks-compat-artifact = { workspace = true }
foks-crypto = { workspace = true }
foks-keystore = { workspace = true }
foks-proto = { workspace = true }
foks-protocol-metadata = { workspace = true }
foks-rpc = { workspace = true }
foks-verify = { workspace = true }
foks-yubi = { workspace = true }
fs2 = { workspace = true }
getrandom = { workspace = true }
libc = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
url = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
foks-server-db = { workspace = true }
foks-client = { workspace = true, features = ["test-support"] }
foks-server-testkit = { workspace = true }
rusqlite = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
