//! Extended chat context binding. Membership, sender assertions and semantic
//! projections remain the caller's responsibility; shared keys are not signatures.
use super::*;
use foks_proto::{RealtimeWire, RtChatContext};

/// Assigned local domains: first eight bytes of SHA-256 of the ASCII labels
/// `fennec.chat.v2.context-key` and `fennec.chat.v2.encrypted-body` respectively.
/// These are not upstream Go type IDs.
const CONTEXT_KEY: u64 = 0xa390_64b7_69c6_b249;
const ENCRYPTED_BODY: u64 = 0x16b0_1866_0207_d95c;
pub const CHAT_V2_MAX_PLAINTEXT_BYTES: usize = 64 * 1024;

fn key(seed: &SecretSeed, context: &RtChatContext) -> Result<Zeroizing<[u8; 32]>> {
    Ok(Zeroizing::new(typed_hmac(
        seed.as_slice(),
        CONTEXT_KEY,
        &context.encoded()?,
    )))
}

/// The caller supplies a fresh random nonce and persists the exact resulting
/// ciphertext before attempting a durable operation. Retries reuse those bytes.
pub fn seal_chat_v2(
    seed: &SecretSeed,
    context: &RtChatContext,
    plaintext: &[u8],
    nonce: [u8; 16],
) -> Result<SecretBox> {
    if plaintext.len() > CHAT_V2_MAX_PLAINTEXT_BYTES {
        return Err(Error::Realtime);
    }
    let key = key(seed, context)?;
    let ciphertext = seal_typed_secretbox(&key, ENCRYPTED_BODY, &nonce, plaintext, false)
        .map_err(|_| Error::Realtime)?;
    Ok(SecretBox { nonce, ciphertext })
}

/// Select the verified historical key identified by context.key before calling.
/// The context includes format, host/team/channel, actor, operation/event IDs,
/// purpose, targets/root, key role/generation and public action metadata.
pub fn open_chat_v2(
    seed: &SecretSeed,
    context: &RtChatContext,
    boxed: &SecretBox,
) -> Result<Zeroizing<Vec<u8>>> {
    if boxed.ciphertext.len() > CHAT_V2_MAX_PLAINTEXT_BYTES + 16 {
        return Err(Error::Realtime);
    }
    let key = key(seed, context)?;
    open_typed_secretbox(&key, ENCRYPTED_BODY, &boxed.nonce, &boxed.ciphertext)
}

#[cfg(test)]
mod tests {
    use super::*;
    use foks_proto::*;
    fn entity(kind: u8, tag: u8) -> EntityId {
        let mut bytes = vec![tag; 33];
        bytes[0] = kind;
        EntityId::from_bytes(bytes).unwrap()
    }
    fn context() -> RtChatContext {
        RtChatContext {
            host: RtHostId::new(entity(ENTITY_HOST, 1)).unwrap(),
            team: RtTeamId::new(entity(ENTITY_NAMED_TEAM, 2)).unwrap(),
            channel: RtChannelId([3; 16]),
            actor: RtUserId::new(entity(ENTITY_USER, 4)).unwrap(),
            operation: RtChatOperationId::new([5; 16]).unwrap(),
            key: RoleAndGeneration {
                role: Role::member(0),
                generation: 1,
            },
            purpose: RtChatPurpose::Reply {
                event: RtChatEventId::new([6; 16]).unwrap(),
                target: RtChatEventId::new([7; 16]).unwrap(),
                root: RtChatEventId::new([8; 16]).unwrap(),
            },
        }
    }
    #[test]
    fn every_context_field_is_authenticated() {
        let seed = SecretSeed::new([9; 32]);
        let original = context();
        let boxed = seal_chat_v2(&seed, &original, b"original text", [10; 16]).unwrap();
        // Independent Python HMAC + libsodium oracle, not generated by Rust.
        assert_eq!(
            original.encoded().unwrap(),
            include_bytes!("../tests/fixtures/chat-v2/context.snowp")
        );
        assert_eq!(
            key(&seed, &original).unwrap().as_slice(),
            include_bytes!("../tests/fixtures/chat-v2/key.bin")
        );
        assert_eq!(
            boxed.ciphertext,
            include_bytes!("../tests/fixtures/chat-v2/ciphertext.bin")
        );
        assert_eq!(
            open_chat_v2(&seed, &original, &boxed).unwrap().as_slice(),
            b"original text"
        );
        let altered_id = RtChatEventId::new([20; 16]).unwrap();
        let mut variants = Vec::new();
        macro_rules! changed {
            ($field:ident, $value:expr) => {{
                let mut c = original.clone();
                c.$field = $value;
                variants.push(c);
            }};
        }
        changed!(host, RtHostId::new(entity(ENTITY_HOST, 20)).unwrap());
        changed!(team, RtTeamId::new(entity(ENTITY_NAMED_TEAM, 20)).unwrap());
        changed!(channel, RtChannelId([20; 16]));
        changed!(actor, RtUserId::new(entity(ENTITY_USER, 20)).unwrap());
        changed!(operation, RtChatOperationId::new([20; 16]).unwrap());
        changed!(
            key,
            RoleAndGeneration {
                role: Role::ADMIN,
                generation: 1
            }
        );
        changed!(
            key,
            RoleAndGeneration {
                role: Role::member(0),
                generation: 2
            }
        );
        for changed_field in 0..3 {
            let mut c = original.clone();
            let RtChatPurpose::Reply {
                event,
                target,
                root,
            } = &mut c.purpose
            else {
                unreachable!()
            };
            *match changed_field {
                0 => event,
                1 => target,
                _ => root,
            } = altered_id;
            variants.push(c);
        }
        changed!(purpose, RtChatPurpose::Message { event: altered_id });
        for context in variants {
            assert!(
                open_chat_v2(&seed, &context, &boxed).is_err(),
                "accepted {context:?}"
            );
        }
        assert!(open_chat_v2(&SecretSeed::new([21; 32]), &original, &boxed).is_err());
        let mut altered = boxed.clone();
        altered.nonce[0] ^= 1;
        assert!(open_chat_v2(&seed, &original, &altered).is_err());
        altered = boxed;
        altered.ciphertext[0] ^= 1;
        assert!(open_chat_v2(&seed, &original, &altered).is_err());
    }
    #[test]
    fn action_metadata_and_body_limits_are_authenticated() {
        let seed = SecretSeed::new([9; 32]);
        let mut original = context();
        let event = RtChatEventId::new([6; 16]).unwrap();
        let target = RtChatEventId::new([7; 16]).unwrap();
        for (a, b) in [
            (
                RtChatPurpose::Delete {
                    event,
                    target,
                    moderation: false,
                },
                RtChatPurpose::Delete {
                    event,
                    target,
                    moderation: true,
                },
            ),
            (
                RtChatPurpose::Reaction {
                    event,
                    target,
                    key: [1; 32],
                    present: true,
                },
                RtChatPurpose::Reaction {
                    event,
                    target,
                    key: [1; 32],
                    present: false,
                },
            ),
            (
                RtChatPurpose::Reaction {
                    event,
                    target,
                    key: [1; 32],
                    present: true,
                },
                RtChatPurpose::Reaction {
                    event,
                    target,
                    key: [2; 32],
                    present: true,
                },
            ),
            (
                RtChatPurpose::Name {
                    revision: RtChatRevision::new(1).unwrap(),
                },
                RtChatPurpose::Name {
                    revision: RtChatRevision::new(2).unwrap(),
                },
            ),
            (
                RtChatPurpose::Name {
                    revision: RtChatRevision::new(1).unwrap(),
                },
                RtChatPurpose::Description {
                    revision: RtChatRevision::new(1).unwrap(),
                },
            ),
        ] {
            original.purpose = a;
            let boxed = seal_chat_v2(&seed, &original, b"body", [10; 16]).unwrap();
            original.purpose = b;
            assert!(open_chat_v2(&seed, &original, &boxed).is_err());
        }
        let maximum = vec![1; CHAT_V2_MAX_PLAINTEXT_BYTES];
        let boxed = seal_chat_v2(&seed, &original, &maximum, [11; 16]).unwrap();
        assert_eq!(
            open_chat_v2(&seed, &original, &boxed).unwrap().as_slice(),
            maximum
        );
        assert!(seal_chat_v2(
            &seed,
            &original,
            &vec![1; CHAT_V2_MAX_PLAINTEXT_BYTES + 1],
            [12; 16]
        )
        .is_err());
        let oversized = SecretBox {
            nonce: [11; 16],
            ciphertext: vec![0; CHAT_V2_MAX_PLAINTEXT_BYTES + 17],
        };
        assert!(open_chat_v2(&seed, &original, &oversized).is_err());
    }
}
