use std::time::Duration;

#[derive(Clone, Debug)]
pub struct Config {
    pub busy_timeout: Duration,
    pub maximum_name_bytes: usize,
    pub maximum_blob_bytes: usize,
    pub maximum_receipt_bytes: usize,
    pub maximum_merkle_nodes_per_commit: usize,
    pub maximum_back_pointers: usize,
    pub maximum_active_credentials_per_user: usize,
    pub maximum_backup_credentials_per_user: usize,
    pub maximum_user_chain_links: u64,
    pub maximum_team_chain_links: u64,
    pub maximum_teams: usize,
    pub maximum_team_members: usize,
    pub maximum_team_role_bands: usize,
    pub maximum_team_name_reservations: usize,
    pub maximum_boxes_per_mutation: usize,
    pub maximum_active_recovery_challenges: usize,
    pub maximum_recovery_challenges_per_entity: usize,
    pub maximum_passphrase_generations: u64,
    pub maximum_active_passphrase_challenges: usize,
    pub maximum_passphrase_challenges_per_user: usize,
    pub maximum_bad_passphrase_attempts: usize,
    pub bad_passphrase_window: Duration,
    pub maximum_team_view_capabilities_per_pair: usize,
    pub maximum_active_team_view_capabilities: usize,
    pub maximum_team_admin_capabilities_per_pair: usize,
    pub maximum_active_team_admin_capabilities: usize,
    pub maximum_kv_node_bytes: usize,
    pub maximum_kv_namespace_bytes: u64,
    pub maximum_kv_namespace_objects: u64,
    pub maximum_database_bytes: u64,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            busy_timeout: Duration::from_secs(5),
            maximum_name_bytes: 255,
            maximum_blob_bytes: 16 * 1024 * 1024,
            maximum_receipt_bytes: 16 * 1024 * 1024,
            maximum_merkle_nodes_per_commit: 131_072,
            maximum_back_pointers: 64,
            maximum_active_credentials_per_user: 16,
            maximum_backup_credentials_per_user: 4,
            maximum_user_chain_links: 4096,
            maximum_team_chain_links: 4096,
            maximum_teams: 4096,
            maximum_team_members: 64,
            maximum_team_role_bands: 16,
            maximum_team_name_reservations: 4096,
            maximum_boxes_per_mutation: 1024,
            maximum_active_recovery_challenges: 4096,
            maximum_recovery_challenges_per_entity: 8,
            maximum_passphrase_generations: 4096,
            maximum_active_passphrase_challenges: 4096,
            maximum_passphrase_challenges_per_user: 8,
            maximum_bad_passphrase_attempts: 5,
            bad_passphrase_window: Duration::from_secs(10 * 60),
            maximum_team_view_capabilities_per_pair: 32,
            maximum_active_team_view_capabilities: 16_384,
            maximum_team_admin_capabilities_per_pair: 32,
            maximum_active_team_admin_capabilities: 16_384,
            maximum_kv_node_bytes: 64 * 1024,
            maximum_kv_namespace_bytes: 16 * 1024 * 1024 * 1024,
            maximum_kv_namespace_objects: 1_000_000,
            maximum_database_bytes: 64 * 1024 * 1024 * 1024,
        }
    }
}
